### PR TITLE
fix(cli): don't check cdktf-cli version

### LINKED ISSUE #98: cdktn-cli: checking cdktf-cli for new versions
### Expected Behavior

The CLI checks if a new version is available and reports if so.

### Actual Behavior

https://github.com/open-constructs/cdk-terrain/blob/cf470bb938c1ad6bcee68f7507f3ab71bbc91a73/packages/cdktn-cli/src/bin/cmds/helper/version-check.ts#L78

cdktn-cli is still checking if a new version of cdktf-cli is available. It should be checking cdktn-cli now that it has been released to npm.

### Steps to Reproduce

1. Delete the version cache at `~/.cdktf/cache/version`, if the file is present
2. Run cdktn
3. No new version reported

### Versions

cdktn-cli: 0.22.0

### Migration Context

I used cdktf and did NOT see this issue there (possible regression)

### Upstream cdktf Issue

_No response_

### Providers

_No response_

### Gist

_No response_

### Possible Solutions

_No response_

### Workarounds

_No response_

### Anything Else?

_No response_

### References

_No response_

### Help Wanted

- [x] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by gabegorelick**
The CLI checks if there's a newer version available on npm. But it's currently checking if there's a newer version of `cdktf-cli`, not `cdktn-cli`. This was intentional while cdktn-cli hadn't had a release yet. But now that it has been released to npm, we can update this check.

### Related issue

Fixes #98

### Description

cdktf-cli -> cdktn-cli

### Checklist

- [x] I have updated the PR title to match [CDKTN's style guide](https://github.com/open-constructs/cdk-terrain/blob/main/CONTRIBUTING.md#pull-requests-1)
- [ ] I have run the linter on my code locally
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/open-constructs/cdk-terrain/tree/main/website) if applicable
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works if applicable
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/cdktn-cli/src/bin/cmds/helper/version-check.ts [hunk 1]
```diff
@@ -74,8 +74,7 @@ export async function latestVersionIfHigher(
     return null;
   }
 
-  // TODO: Check for cdktn-cli after release 1
-  const { stdout, stderr } = await exec("npm view cdktf-cli version");
+  const { stdout, stderr } = await exec("npm view cdktn-cli version");
```
Comment (gabegorelick) [inline packages/cdktn-cli/src/bin/cmds/helper/version-check.ts:77]: `npm view cdktn-cli version` works fine:

Image

**Review by jsteinich — APPROVED** [review]
